---

- ldap_entry:
    dn: "uid=testuser,ou=people,{{ ldap['basedn'] }}"
    objectClass:
      - inetOrgPerson
      - eduPerson
      - schacLinkageIdentifiers
      - schacEntryMetadata
    attributes:
      uid: "testuser"
      sn: "User"
      givenName: "Test"
      cn: "Test User"
      schacPersonalUniqueID: "urn:schac:personalUniqueID:IT:CF:TSTUSR17F08G321G"
      mail: "testuser@{{ ldap['domain'] }}"
      eduPersonAffiliation: "member"
