---
# tasks file for apache
- name: "Include OS-specific variables."
  include_vars: "{{ ansible_os_family }}.yml"
  tags: httpd

- name: "Install Apache"
  import_tasks: httpd-install.yml
  tags: httpd

- name: "Configure Apache"
  import_tasks: httpd-configure.yml
  tags: httpd
