---
# file: shib-idp-idm-servers.yml
- hosts: Debian-IdP-with-IdM
  become: yes
  become_method: sudo
  remote_user: debian
  roles:
    - common
    - apache
    - jdk
    - jetty
    - openldap
    - flup
    - mysql
    - idp
    - phpldapadmin
    - check_mk_agent
    - rsync
    - sys-update
