---
# tasks file for Statistics application
- name: "Debian 8 - Install packages needed by /statistics application"
  apt:
   name: "{{item}}"
   state: latest
   update_cache: yes
  with_items:
   - python-mysqldb
   - php5-mysql
   - php5
  when:
   - ansible_distribution_release == "jessie"
  tags: idp

#- name: "Debian 9 - Install packages needed by /statistics application"
#   apt:
#   name: "{{item}}"
#   state: latest
#   update_cache: yes
#  with_items:
#   - python-mysqldb
#   - php7.0-mysql
#   - php7.0-xml
#   - php7.0
#  when:
#   - ansible_distribution_release == "stretch"
#  tags: idp

- name: "Check if 'statistics' DB is already created and store the result into 'statistics_db' ansible variable"
  command: mysql -u root -s -N -e "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME='statistics'"
  register: statistics_db
  changed_when: false
  tags: idp

- name: "Create 'loganalysis' directory"
  file:
   dest: "/opt/loganalysis"
   owner: "root"
   group: "root"
   mode: "0644"
   state: directory
  tags: idp

- name: "Create 'statistics' directory"
  file:
   dest: "/var/www/html/statistics"
   owner: "root"
   group: "root"
   mode: "0755"
   state: directory
  notify:
   - "Restart Apache"
  tags: idp

- name: "Load /statistics Configuration files - Part 1"
  template:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "root"
   group: "root"
   mode: "{{ item.mode }}"
  with_items:
   - { src: "statistics/statistics-idp-db.sql.j2", dest: "/root/statistics-idp-db.sql", mode: "0600" }
   - { src: "statistics/dbanalysis.py.j2", dest: "/opt/loganalysis/dbanalysis.py", mode: "0600" }
   - { src: "statistics/config.php.j2", dest: "/opt/loganalysis/config.php", mode: "0644" }
   - { src: "statistics/insertSP.php.j2", dest: "/opt/loganalysis/insertSP.php", mode: "0644" }
   - { src: "statistics/IDProvider.conf.php.j2", dest: "/opt/loganalysis/IDProvider.conf.php", mode: "0644" }
   - { src: "statistics/db.php.j2", dest: "/var/www/html/statistics/db.php", mode: "0644" }
  tags: idp

- name: "Load /statistics Configuration files - Parte 2"
  copy:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "{{ item.owner }}"
   group: "{{ item.group }}"
   mode: "{{ item.mode }}"
  with_items:
   - { src: "files/statistics/conf/", dest: "/opt/loganalysis/", owner: "root", group: "root", mode: "0644" }
   - { src: "files/statistics/cron/cron-idp-stats", dest: "/etc/cron.daily/cron-idp-stats", owner: "root", group: "root", mode: "0755" }
   - { src: "files/statistics/apache/idp-stats.conf", dest: "/etc/apache2/conf-enabled/idp-stats.conf", owner: "root", group: "root", mode: "0644" }
  notify:
   - "Restart Apache"
  tags: idp

- name: "Create 'statistics' database"
  mysql_db:
   encoding: "utf8"
   state: import
   name: all
   target: "/root/statistics-idp-db.sql"
  when: statistics_db.stdout != 'statistics'
  tags: idp

- name: "Link the federation metadata file used by /statistics"
  file:
   src: "/opt/shibboleth-idp/metadata/{{ idp_stats['fed_md'] }}"
   dest: "/opt/loganalysis/{{ idp_stats['fed_md'] }}"
   owner: "root"
   group: "root"
   state: "link"
  tags: idp

- name: "Load Statistic Web Application files in the right position"
  copy:
   src: "files/statistics/apache/www/"
   dest: "/var/www/html/statistics/"
   owner: "root"
   group: "root"
   mode: "0644"
  notify:
   - "Restart Apache"
  tags: idp
